package interfacesEntornos2;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * Clase para crear una ventana de selección de ataque.&nbsp;Con un título, 3 RadioButton para seleccionar el ataque y dos botones (uno muestra un MessageDialog según la selección de RadioButton y el otro cierra la aplicación).
 * @author Eric_
 * @version 1
 */
public class Fight extends javax.swing.JFrame {

    /**
     * Constructor de la clase que inicializa los componentes y ubica la ventana en el centro de la pantalla.
     */
    public Fight() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ataques = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        melee = new javax.swing.JRadioButton();
        sing = new javax.swing.JRadioButton();
        ranged = new javax.swing.JRadioButton();
        jBExit = new javax.swing.JButton();
        jBContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 0, 28)); // NOI18N
        jLabel1.setText("HOW YOU'RE GOING TO ATTACK");

        Ataques.add(melee);
        melee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        melee.setText("MELEE ATTACK");

        Ataques.add(sing);
        sing.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sing.setText("SING");

        Ataques.add(ranged);
        ranged.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ranged.setText("RANGED ATTACK");

        jBExit.setFont(new java.awt.Font("Source Code Pro Light", 0, 24)); // NOI18N
        jBExit.setText("EXIT");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        jBContinue.setFont(new java.awt.Font("Source Code Pro Light", 0, 24)); // NOI18N
        jBContinue.setText("DO YOUR THING");
        jBContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(melee)
                                .addGap(18, 18, 18)
                                .addComponent(sing)
                                .addGap(29, 29, 29)
                                .addComponent(ranged))
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBExit)
                        .addGap(212, 212, 212))))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jBContinue)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(melee, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sing, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ranged, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jBContinue)
                .addGap(26, 26, 26)
                .addComponent(jBExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "EXIT" y termina la aplicación.
     * @param evt Acción que provoca la ejecución del método.
     */
    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBExitActionPerformed

    /**
     * Muestra un MessageDialog según la selección de RadioButton.<br><br>
     * Las opciones son:<br>
     * - Seleccionas melee: Muerte.<br>
     * - Seleccionas cantar: Final pacífico.<br>
     * - Seleccionas rango: Muerte.<br>
     * @param evt Acción que provoca la ejecución del método.
     */
    private void jBContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinueActionPerformed
        if (melee.isSelected()) {
            JOptionPane.showMessageDialog(this, "Sans pierces your chest with his bare hands\n*You die*");
            System.exit(0);
        }
        else if (ranged.isSelected()) {
            JOptionPane.showMessageDialog(this, "Sans shots you a beam with his magic eye\n*You die burned*");
            System.exit(0);
        }
        else {
            JOptionPane.showMessageDialog(this, "Sans starts singing with you. You two sing 4 more songs together and become best friends");
            System.exit(0);
        }
    }//GEN-LAST:event_jBContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Ataques;
    private javax.swing.JButton jBContinue;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton melee;
    private javax.swing.JRadioButton ranged;
    private javax.swing.JRadioButton sing;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que cambia el icono predeterminado de la ventana por la imagen indicada.
     * @return La imagen seleccionada como icono de la ventana.
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("img/sansface.png"));
        return retValue;
    }
    
}
