package interfacesEntornos2;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * Clase para crear una ventana que confirma el inicio de sesión.&nbsp;Con un título y dos botones (uno que empieza el juego de Sans y el otro cierra la aplicación).
 * @author Eric_
 * @version 1
 */
public class Login extends javax.swing.JFrame {
    /**
     * Entero privado que almacena el valor de "badSans".
     */
    private int badSans = 1;
    /**
     * Constructor de la clase que inicializa los componentes de la ventana y la ubica en el centro de la pantalla.
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jBSans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 0, 28)); // NOI18N
        jLabel1.setText("YOU'RE LOGGED IN");

        jBExit.setFont(new java.awt.Font("Source Code Pro Light", 0, 24)); // NOI18N
        jBExit.setText("EXIT");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        jBSans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sans.png"))); // NOI18N
        jBSans.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/badsans.png"))); // NOI18N
        jBSans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBExit)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "EXIT" y termina la aplicación.
     * @param evt Acción que provoca la ejecución del método.
     */
    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBExitActionPerformed

    /**
     * Método que se ejecuta al hacer clic en el botón "Sans" y realiza una acción dependiendo del valor de "badSans".<br><br>
     * Las acciones según el valor són:<br>
     * - <code>badSans = 1</code> &nbsp;Muestra un MessageDialog de aviso.<br>
     * - <code>badSans = 2</code> &nbsp;Muestra un MessageDialog de último aviso.<br>
     * - <code>badSans = 3</code> &nbsp;Abre la ventana del JFrame "Weapons" y cierra esta ventana.
     * @param evt Acción que provoca la ejecución del método.
     */
    private void jBSansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSansActionPerformed
        switch (badSans) {
            case 1:
                badSans++;
                JOptionPane.showMessageDialog(this, "Don't touch me", "SANS", 1);
                break;
            case 2:
                badSans++;
                JOptionPane.showMessageDialog(this, "DON'T TOUCH ME", "SANS", 1);
                break;
            default:
                Weapons ventana = new Weapons();
                ventana.setVisible(true);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jBSansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBSans;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que cambia el icono predeterminado de la ventana por la imagen indicada.
     * @return La imagen seleccionada como icono de la ventana.
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("img/sansface.png"));
        return retValue;
    }
    
}
